import {
  Product,
  Order,
  Store,
  Category,
  Coupon,
  DeliveryAgent,
  CartItem,
  User,
  Address,
  AnalyticsData,
  BusinessMetrics,
} from './types'

export const categories: Category[] = [
  { id: 'fruits', name: 'Fresh Fruits', icon: '🍎', description: 'Fresh and organic fruits', color: 'bg-red-50' },
  { id: 'vegetables', name: 'Vegetables', icon: '🥦', description: 'Fresh vegetables daily', color: 'bg-green-50' },
  { id: 'dairy', name: 'Dairy & Eggs', icon: '🥛', description: 'Fresh dairy products', color: 'bg-blue-50' },
  { id: 'bakery', name: 'Bakery', icon: '🥐', description: 'Fresh baked goods', color: 'bg-amber-50' },
  { id: 'meat', name: 'Meat & Fish', icon: '🍗', description: 'Premium quality meat', color: 'bg-pink-50' },
  { id: 'pantry', name: 'Pantry Staples', icon: '🍚', description: 'Essential pantry items', color: 'bg-yellow-50' },
  { id: 'dal', name: 'Dals & Legumes', icon: '🫘', description: 'Lentils and pulses', color: 'bg-orange-50' },
  { id: 'spices', name: 'Spices & Masalas', icon: '🌶️', description: 'Authentic spices and masalas', color: 'bg-red-100' },
  { id: 'tea', name: 'Tea & Coffee', icon: '☕', description: 'Premium tea and coffee', color: 'bg-amber-100' },
  { id: 'biscuits', name: 'Biscuits & Cookies', icon: '🍪', description: 'Crispy biscuits and cookies', color: 'bg-yellow-100' },
  { id: 'snacks', name: 'Snacks', icon: '🥨', description: 'Tasty snacks and treats', color: 'bg-purple-50' },
  { id: 'colddrinks', name: 'Cold Drinks', icon: '🥤', description: 'Refreshing cold beverages', color: 'bg-blue-100' },
  { id: 'icecream', name: 'Ice Cream', icon: '🍦', description: 'Frozen desserts', color: 'bg-pink-100' },
  { id: 'bodycare', name: 'Body Care', icon: '🧴', description: 'Personal hygiene products', color: 'bg-green-100' },
  { id: 'oils', name: 'Cooking Oils', icon: '🫒', description: 'Premium cooking oils', color: 'bg-yellow-200' },
  { id: 'beverages', name: 'Beverages', icon: '☕', description: 'Drinks and juices', color: 'bg-cyan-50' },
]

export const mockProducts: Product[] = [
  // Fruits
  {
    id: '1',
    name: 'Fresh Red Apples',
    brand: 'Nature Fresh',
    category: 'Fresh Fruits',
    categoryId: 'fruits',
    price: 4.99,
    originalPrice: 6.99,
    discount: 28,
    image: '/products/fresh-apple.png',
    brandLogo: '🍎',
    description: 'Crisp, sweet red apples, perfect for healthy snacking and baking',
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    unit: 'lb',
    nutritionInfo: '95 cal, 25g carbs, 4g fiber per 100g',
  },
  {
    id: '2',
    name: 'Organic Bananas',
    brand: 'Eco Harvest',
    category: 'Fresh Fruits',
    categoryId: 'fruits',
    price: 2.49,
    image: '/products/fresh-bananas.png',
    brandLogo: '🍌',
    description: 'Ripe, creamy bananas, rich in potassium',
    rating: 4.6,
    reviewCount: 412,
    inStock: true,
    unit: 'lb',
  },
  {
    id: '3',
    name: 'Fresh Oranges',
    brand: 'Citrus Gold',
    category: 'Fresh Fruits',
    categoryId: 'fruits',
    price: 5.99,
    originalPrice: 7.99,
    discount: 25,
    image: '/products/fresh-oranges.png',
    brandLogo: '🍊',
    description: 'Juicy oranges, high in vitamin C',
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    unit: 'lb',
  },

  // Vegetables
  {
    id: '4',
    name: 'Fresh Tomatoes',
    brand: 'Farm Fresh',
    category: 'Vegetables',
    categoryId: 'vegetables',
    price: 3.49,
    originalPrice: 4.99,
    discount: 30,
    image: '/products/fresh-tomatoes.png',
    brandLogo: '🍅',
    description: 'Ripe, juicy tomatoes perfect for salads and cooking',
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    unit: 'lb',
  },
  {
    id: '5',
    name: 'Fresh Carrots',
    brand: 'Garden Harvest',
    category: 'Vegetables',
    categoryId: 'vegetables',
    price: 2.99,
    image: '/products/fresh-carrots.png',
    brandLogo: '🥕',
    description: 'Sweet, crunchy carrots, great for salads and cooking',
    rating: 4.7,
    reviewCount: 167,
    inStock: true,
    unit: 'lb',
  },
  {
    id: '6',
    name: 'Fresh Spinach',
    brand: 'Leafy Greens Co',
    category: 'Vegetables',
    categoryId: 'vegetables',
    price: 3.99,
    image: '/products/fresh-spinach.png',
    brandLogo: '🥬',
    description: 'Organic spinach leaves, 10oz bag, nutrient-rich',
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    unit: 'bag',
  },

  // Dairy & Eggs
  {
    id: '7',
    name: 'Organic Whole Milk',
    brand: 'Meadow Fresh',
    category: 'Dairy & Eggs',
    categoryId: 'dairy',
    price: 4.49,
    image: '/products/organic-milk.png',
    brandLogo: '🥛',
    description: 'Premium organic whole milk, 1 gallon',
    rating: 4.7,
    reviewCount: 334,
    inStock: true,
    unit: 'gallon',
  },
  {
    id: '8',
    name: 'Free-Range Brown Eggs',
    brand: 'Happy Hens',
    category: 'Dairy & Eggs',
    categoryId: 'dairy',
    price: 5.99,
    originalPrice: 7.99,
    discount: 25,
    image: '/products/brown-eggs.png',
    brandLogo: '🥚',
    description: 'Dozen free-range organic brown eggs',
    rating: 4.9,
    reviewCount: 289,
    inStock: true,
    unit: 'dozen',
  },
  {
    id: '9',
    name: 'Greek Yogurt',
    brand: 'Greek Bliss',
    category: 'Dairy & Eggs',
    categoryId: 'dairy',
    price: 4.99,
    image: '/products/greek-yogurt.png',
    brandLogo: '🥛',
    description: 'Creamy Greek yogurt, 32oz container, probiotic',
    rating: 4.6,
    reviewCount: 267,
    inStock: true,
    unit: 'container',
  },

  // Bakery
  {
    id: '10',
    name: 'Whole Wheat Bread',
    brand: 'Artisan Bake',
    category: 'Bakery',
    categoryId: 'bakery',
    price: 3.99,
    image: '/products/whole-wheat-bread.png',
    brandLogo: '🍞',
    description: 'Freshly baked whole wheat bread, 24oz loaf',
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    unit: 'loaf',
  },
  {
    id: '11',
    name: 'Premium Granola',
    brand: 'Cereal Master',
    category: 'Bakery',
    categoryId: 'bakery',
    price: 6.99,
    image: '/products/granola-cereal.png',
    brandLogo: '🥣',
    description: 'Healthy granola with nuts and dried fruits, 16oz',
    rating: 4.6,
    reviewCount: 178,
    inStock: true,
    unit: 'box',
  },

  // Pantry Staples
  {
    id: '12',
    name: 'Basmati Rice',
    brand: 'Rice King',
    category: 'Pantry Staples',
    categoryId: 'pantry',
    price: 8.99,
    image: '/products/rice-package.png',
    brandLogo: '🍚',
    description: 'Premium basmati rice, 2lb package',
    rating: 4.7,
    reviewCount: 212,
    inStock: true,
    unit: 'bag',
  },
  {
    id: '13',
    name: 'Extra Virgin Olive Oil',
    brand: 'Mediterranean Gold',
    category: 'Pantry Staples',
    categoryId: 'pantry',
    price: 12.99,
    image: '/products/olive-oil.png',
    brandLogo: '🫒',
    description: 'Premium extra virgin olive oil, 500ml bottle',
    rating: 4.8,
    reviewCount: 145,
    inStock: true,
    unit: 'bottle',
  },
  {
    id: '14',
    name: 'Canned Beans',
    brand: 'Bean Co',
    category: 'Pantry Staples',
    categoryId: 'pantry',
    price: 1.99,
    image: '/products/canned-beans.png',
    brandLogo: '🫘',
    description: 'Organic canned beans, 15oz can',
    rating: 4.5,
    reviewCount: 98,
    inStock: true,
    unit: 'can',
  },

  // Beverages
  {
    id: '15',
    name: 'Premium Coffee Beans',
    brand: 'Brew Masters',
    category: 'Beverages',
    categoryId: 'beverages',
    price: 11.99,
    image: '/products/premium-coffee.png',
    brandLogo: '☕',
    description: 'Single-origin premium coffee beans, 1lb bag',
    rating: 4.8,
    reviewCount: 267,
    inStock: true,
    unit: 'bag',
  },
  {
    id: '16',
    name: 'Fresh Orange Juice',
    brand: 'Pure Juice',
    category: 'Beverages',
    categoryId: 'beverages',
    price: 4.99,
    image: '/products/orange-juice.png',
    brandLogo: '🍊',
    description: 'Fresh squeezed orange juice, 64oz bottle',
    rating: 4.6,
    reviewCount: 134,
    inStock: true,
    unit: 'bottle',
  },

  // Dals & Legumes
  {
    id: '17',
    name: 'Red Masoor Dal',
    brand: 'Dal Delights',
    category: 'Dals & Legumes',
    categoryId: 'dal',
    price: 3.49,
    originalPrice: 4.49,
    discount: 22,
    image: '/products/red-dal.png',
    description: 'Premium red masoor dal, rich in protein and fiber',
    rating: 4.7,
    reviewCount: 156,
    inStock: true,
    unit: 'lb',
  },
  {
    id: '18',
    name: 'Yellow Moong Dal',
    brand: 'Dal Delights',
    category: 'Dals & Legumes',
    categoryId: 'dal',
    price: 2.99,
    image: '/products/red-dal.png',
    description: 'Pure yellow moong dal, easy to digest',
    rating: 4.6,
    reviewCount: 123,
    inStock: true,
    unit: 'lb',
  },
  {
    id: '19',
    name: 'Black Chickpeas',
    brand: 'Legume King',
    category: 'Dals & Legumes',
    categoryId: 'dal',
    price: 3.99,
    image: '/products/red-dal.png',
    description: 'Organic black chickpeas, nutritious and filling',
    rating: 4.8,
    reviewCount: 189,
    inStock: true,
    unit: 'lb',
  },

  // Spices & Masalas
  {
    id: '20',
    name: 'Pure Turmeric Powder',
    brand: 'Golden Spice',
    category: 'Spices & Masalas',
    categoryId: 'spices',
    price: 4.99,
    originalPrice: 6.49,
    discount: 23,
    image: '/products/turmeric-powder.png',
    description: 'Pure turmeric powder with anti-inflammatory benefits',
    rating: 4.9,
    reviewCount: 267,
    inStock: true,
    unit: '100g',
  },
  {
    id: '21',
    name: 'Garam Masala Blend',
    brand: 'Spice Master',
    category: 'Spices & Masalas',
    categoryId: 'spices',
    price: 5.99,
    image: '/products/garam-masala.png',
    description: 'Authentic garam masala blend for Indian cooking',
    rating: 4.8,
    reviewCount: 198,
    inStock: true,
    unit: '100g',
  },
  {
    id: '22',
    name: 'Red Chili Powder',
    brand: 'Spice Master',
    category: 'Spices & Masalas',
    categoryId: 'spices',
    price: 3.49,
    image: '/products/garam-masala.png',
    description: 'Ground red chili powder, adds perfect heat',
    rating: 4.7,
    reviewCount: 145,
    inStock: true,
    unit: '100g',
  },

  // Tea & Coffee
  {
    id: '23',
    name: 'Assam Black Tea',
    brand: 'Tea Time',
    category: 'Tea & Coffee',
    categoryId: 'tea',
    price: 6.99,
    originalPrice: 8.99,
    discount: 22,
    image: '/products/tea-powder.png',
    description: 'Premium Assam black tea leaves, rich and aromatic',
    rating: 4.8,
    reviewCount: 234,
    inStock: true,
    unit: '200g',
  },
  {
    id: '24',
    name: 'Premium Instant Coffee',
    brand: 'Coffee Bliss',
    category: 'Tea & Coffee',
    categoryId: 'tea',
    price: 7.99,
    image: '/products/instant-coffee.png',
    description: 'Instant coffee powder, quick and delicious',
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    unit: '100g',
  },
  {
    id: '25',
    name: 'Green Tea Bags',
    brand: 'Health Brew',
    category: 'Tea & Coffee',
    categoryId: 'tea',
    price: 4.99,
    image: '/products/tea-powder.png',
    description: 'Organic green tea bags, antioxidant rich',
    rating: 4.6,
    reviewCount: 167,
    inStock: true,
    unit: '25 bags',
  },

  // Biscuits & Cookies
  {
    id: '26',
    name: 'Digestive Biscuits',
    brand: 'Bake Master',
    category: 'Biscuits & Cookies',
    categoryId: 'biscuits',
    price: 3.99,
    originalPrice: 5.49,
    discount: 27,
    image: '/products/digestive-biscuits.png',
    description: 'Crispy digestive biscuits, perfect tea time snack',
    rating: 4.8,
    reviewCount: 267,
    inStock: true,
    unit: '400g',
  },
  {
    id: '27',
    name: 'Chocolate Chip Cookies',
    brand: 'Sweet Bakery',
    category: 'Biscuits & Cookies',
    categoryId: 'biscuits',
    price: 4.99,
    image: '/products/digestive-biscuits.png',
    description: 'Delicious chocolate chip cookies, freshly baked',
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    unit: '300g',
  },

  // Snacks
  {
    id: '28',
    name: 'Crispy Potato Chips',
    brand: 'Snack Crisp',
    category: 'Snacks',
    categoryId: 'snacks',
    price: 2.99,
    originalPrice: 3.99,
    discount: 25,
    image: '/products/potato-chips.png',
    description: 'Deliciously crispy potato chips, salted to perfection',
    rating: 4.6,
    reviewCount: 234,
    inStock: true,
    unit: '150g',
  },
  {
    id: '29',
    name: 'Trail Mix Nuts',
    brand: 'Healthy Snacks',
    category: 'Snacks',
    categoryId: 'snacks',
    price: 7.99,
    image: '/products/trail-mix.png',
    description: 'Premium trail mix with nuts and dried fruits',
    rating: 4.8,
    reviewCount: 156,
    inStock: true,
    unit: '200g',
  },
  {
    id: '30',
    name: 'Peanut Butter',
    brand: 'Nut Spread',
    category: 'Snacks',
    categoryId: 'snacks',
    price: 5.99,
    image: '/products/peanut-butter.png',
    description: 'Creamy peanut butter, 100% natural',
    rating: 4.7,
    reviewCount: 189,
    inStock: true,
    unit: '350g',
  },

  // Cold Drinks
  {
    id: '31',
    name: 'Cola Soft Drink',
    brand: 'Refreshment Co',
    category: 'Cold Drinks',
    categoryId: 'colddrinks',
    price: 2.49,
    originalPrice: 3.49,
    discount: 29,
    image: '/products/cola-drink.png',
    description: 'Refreshing cola drink, perfect for hot days',
    rating: 4.5,
    reviewCount: 267,
    inStock: true,
    unit: '500ml',
  },
  {
    id: '32',
    name: 'Lemonade Drink',
    brand: 'Fresh Beverages',
    category: 'Cold Drinks',
    categoryId: 'colddrinks',
    price: 2.99,
    image: '/products/cola-drink.png',
    description: 'Freshly prepared lemonade, citrus flavored',
    rating: 4.6,
    reviewCount: 145,
    inStock: true,
    unit: '500ml',
  },
  {
    id: '33',
    name: 'Iced Mango Juice',
    brand: 'Tropical Drinks',
    category: 'Cold Drinks',
    categoryId: 'colddrinks',
    price: 3.99,
    image: '/products/orange-juice.png',
    description: 'Refreshing mango juice with ice, natural flavor',
    rating: 4.7,
    reviewCount: 178,
    inStock: true,
    unit: '600ml',
  },

  // Ice Cream
  {
    id: '34',
    name: 'Vanilla Ice Cream',
    brand: 'Sweet Dreams',
    category: 'Ice Cream',
    categoryId: 'icecream',
    price: 4.99,
    originalPrice: 6.99,
    discount: 29,
    image: '/products/vanilla-ice-cream.png',
    description: 'Creamy vanilla ice cream, premium quality',
    rating: 4.8,
    reviewCount: 267,
    inStock: true,
    unit: '500ml',
  },
  {
    id: '35',
    name: 'Chocolate Ice Cream',
    brand: 'Chill Out',
    category: 'Ice Cream',
    categoryId: 'icecream',
    price: 5.49,
    image: '/products/vanilla-ice-cream.png',
    description: 'Rich chocolate ice cream, decadent taste',
    rating: 4.7,
    reviewCount: 198,
    inStock: true,
    unit: '500ml',
  },

  // Body Care
  {
    id: '36',
    name: 'Body Wash',
    brand: 'Care Plus',
    category: 'Body Care',
    categoryId: 'bodycare',
    price: 5.99,
    originalPrice: 7.99,
    discount: 25,
    image: '/products/body-wash.png',
    description: 'Gentle body wash with natural ingredients',
    rating: 4.7,
    reviewCount: 134,
    inStock: true,
    unit: '300ml',
  },
  {
    id: '37',
    name: 'Shampoo',
    brand: 'Hair Care Pro',
    category: 'Body Care',
    categoryId: 'bodycare',
    price: 6.99,
    image: '/products/shampoo.png',
    description: 'Premium shampoo for all hair types',
    rating: 4.8,
    reviewCount: 267,
    inStock: true,
    unit: '250ml',
  },
  {
    id: '38',
    name: 'Toothpaste',
    brand: 'Dental Fresh',
    category: 'Body Care',
    categoryId: 'bodycare',
    price: 3.99,
    image: '/products/toothpaste.png',
    description: 'Fluoride toothpaste, fresh mint flavor',
    rating: 4.6,
    reviewCount: 189,
    inStock: true,
    unit: '100ml',
  },

  // Cooking Oils
  {
    id: '39',
    name: 'Mustard Oil',
    brand: 'Oil King',
    category: 'Cooking Oils',
    categoryId: 'oils',
    price: 8.99,
    originalPrice: 11.99,
    discount: 25,
    image: '/products/mustard-oil.png',
    description: 'Pure mustard oil, perfect for Indian cooking',
    rating: 4.7,
    reviewCount: 145,
    inStock: true,
    unit: '500ml',
  },
  {
    id: '40',
    name: 'Coconut Oil',
    brand: 'Tropical Oils',
    category: 'Cooking Oils',
    categoryId: 'oils',
    price: 9.99,
    image: '/products/coconut-oil.png',
    description: 'Virgin coconut oil, versatile and healthy',
    rating: 4.8,
    reviewCount: 267,
    inStock: true,
    unit: '500ml',
  },
  {
    id: '41',
    name: 'Dark Chocolate',
    brand: 'Chocolate Bliss',
    category: 'Snacks',
    categoryId: 'snacks',
    price: 6.99,
    image: '/products/dark-chocolate.png',
    description: 'Premium dark chocolate, 70% cocoa',
    rating: 4.8,
    reviewCount: 189,
    inStock: true,
    unit: '100g',
  },
  {
    id: '42',
    name: 'Almond Milk',
    brand: 'Dairy Alternative',
    category: 'Beverages',
    categoryId: 'beverages',
    price: 4.99,
    image: '/products/almond-milk.png',
    description: 'Creamy almond milk, lactose-free',
    rating: 4.6,
    reviewCount: 134,
    inStock: true,
    unit: '1 liter',
  },
]

export const deliveryAgents: DeliveryAgent[] = [
  {
    id: 'agent-1',
    name: 'Raj Kumar',
    phone: '+1-555-0101',
    rating: 4.9,
    avatar: '👨',
    vehicle: 'Bike',
  },
  {
    id: 'agent-2',
    name: 'Priya Sharma',
    phone: '+1-555-0102',
    rating: 4.8,
    avatar: '👩',
    vehicle: 'Scooter',
  },
  {
    id: 'agent-3',
    name: 'Ahmad Hassan',
    phone: '+1-555-0103',
    rating: 4.7,
    avatar: '👨',
    vehicle: 'Bike',
  },
]

export const mockStores: Store[] = [
  {
    id: 'store-1',
    name: 'Downtown Fresh Market',
    image: '/products/fresh-apple.png',
    distance: 0.8,
    rating: 4.8,
    reviewCount: 542,
    deliveryTime: 22,
    deliveryFee: 2.99,
    minOrder: 15,
    address: '123 Main St, Downtown',
    coordinates: { lat: 40.7128, lng: -74.006 },
    isOpen: true,
    agent: deliveryAgents[0],
    coupons: [
      {
        id: 'coupon-1',
        code: 'FRESH20',
        description: '20% off on fresh produce',
        discount: 20,
        discountType: 'percentage',
        minOrder: 25,
        maxUses: 100,
        usedCount: 45,
        expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
        applicableCategories: ['fruits', 'vegetables'],
        isActive: true,
      },
      {
        id: 'coupon-2',
        code: 'WELCOME10',
        description: '$10 off on first order',
        discount: 10,
        discountType: 'fixed',
        minOrder: 30,
        maxUses: 200,
        usedCount: 89,
        expiryDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        isActive: true,
      },
    ],
    specialOffers: [
      {
        id: 'offer-1',
        title: 'Weekend Sale',
        description: 'Special discounts on all bakery items this weekend',
        discount: 25,
        applicableProducts: ['10', '11'],
        startDate: new Date(),
        endDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
      },
    ],
  },
  {
    id: 'store-2',
    name: 'Uptown Premium Grocery',
    image: '/products/fresh-apple.png',
    distance: 1.2,
    rating: 4.7,
    reviewCount: 428,
    deliveryTime: 28,
    deliveryFee: 3.99,
    minOrder: 20,
    address: '456 Oak Ave, Uptown',
    coordinates: { lat: 40.7614, lng: -73.9776 },
    isOpen: true,
    agent: deliveryAgents[1],
    coupons: [
      {
        id: 'coupon-3',
        code: 'DAIRY15',
        description: '15% off on all dairy products',
        discount: 15,
        discountType: 'percentage',
        minOrder: 20,
        maxUses: 150,
        usedCount: 67,
        expiryDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        applicableCategories: ['dairy'],
        isActive: true,
      },
    ],
    specialOffers: [],
  },
  {
    id: 'store-3',
    name: 'Westside Organic Store',
    image: '/products/fresh-apple.png',
    distance: 1.5,
    rating: 4.6,
    reviewCount: 356,
    deliveryTime: 35,
    deliveryFee: 4.99,
    minOrder: 25,
    address: '789 Park Ln, Westside',
    coordinates: { lat: 40.7589, lng: -74.0087 },
    isOpen: true,
    agent: deliveryAgents[2],
    coupons: [],
    specialOffers: [
      {
        id: 'offer-2',
        title: 'Organic Everything',
        description: 'Extra 10% off on all organic items',
        discount: 10,
        applicableProducts: ['1', '6', '8'],
        startDate: new Date(),
        endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
      },
    ],
  },
]

export const coupons: Coupon[] = [
  {
    id: 'coupon-1',
    code: 'FRESH20',
    description: '20% off on fresh produce',
    discount: 20,
    discountType: 'percentage',
    minOrder: 25,
    maxUses: 100,
    usedCount: 45,
    expiryDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    applicableCategories: ['fruits', 'vegetables'],
    isActive: true,
  },
  {
    id: 'coupon-2',
    code: 'WELCOME10',
    description: '$10 off on first order',
    discount: 10,
    discountType: 'fixed',
    minOrder: 30,
    maxUses: 200,
    usedCount: 89,
    expiryDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
  {
    id: 'coupon-3',
    code: 'DELIVERY5',
    description: '$5 off on delivery',
    discount: 5,
    discountType: 'fixed',
    minOrder: 15,
    maxUses: 500,
    usedCount: 234,
    expiryDate: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000),
    isActive: true,
  },
]

export const mockOrders: Order[] = [
  {
    id: 'ORD-001',
    userId: 'user-1',
    storeId: 'store-1',
    items: [
      { productId: '1', product: mockProducts[0], quantity: 2 },
      { productId: '4', product: mockProducts[3], quantity: 1 },
    ],
    totalAmount: 19.47,
    discountAmount: 3.5,
    deliveryFee: 2.99,
    tax: 1.25,
    paymentMethod: {
      id: 'pm-1',
      type: 'card',
      last4: '4242',
      isDefault: true,
    },
    deliveryAddress: {
      id: 'addr-1',
      label: 'Home',
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      coordinates: { lat: 40.7128, lng: -74.006 },
      isDefault: true,
    },
    status: 'out_for_delivery',
    timeline: [
      { status: 'pending', timestamp: new Date(Date.now() - 1000 * 60 * 30), message: 'Order placed' },
      { status: 'confirmed', timestamp: new Date(Date.now() - 1000 * 60 * 25), message: 'Store confirmed order' },
      { status: 'preparing', timestamp: new Date(Date.now() - 1000 * 60 * 15), message: 'Preparing your items' },
      {
        status: 'out_for_delivery',
        timestamp: new Date(Date.now() - 1000 * 60 * 5),
        message: 'Out for delivery',
        location: { lat: 40.7150, lng: -74.005 },
      },
    ],
    deliveryAgent: deliveryAgents[0],
    estimatedDelivery: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 30),
  },
  {
    id: 'ORD-002',
    userId: 'user-1',
    storeId: 'store-1',
    items: [
      { productId: '2', product: mockProducts[1], quantity: 3 },
      { productId: '9', product: mockProducts[8], quantity: 1 },
    ],
    totalAmount: 17.46,
    discountAmount: 2.0,
    deliveryFee: 2.99,
    tax: 1.1,
    paymentMethod: {
      id: 'pm-1',
      type: 'card',
      last4: '4242',
      isDefault: true,
    },
    deliveryAddress: {
      id: 'addr-1',
      label: 'Home',
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      zipCode: '10001',
      coordinates: { lat: 40.7128, lng: -74.006 },
      isDefault: true,
    },
    status: 'delivered',
    timeline: [
      { status: 'pending', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2), message: 'Order placed' },
      { status: 'confirmed', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2 + 5 * 60 * 1000), message: 'Store confirmed order' },
      { status: 'preparing', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1.5), message: 'Preparing your items' },
      { status: 'ready_for_pickup', timestamp: new Date(Date.now() - 1000 * 60 * 60 * 1), message: 'Ready for pickup' },
      { status: 'out_for_delivery', timestamp: new Date(Date.now() - 1000 * 60 * 45), message: 'Out for delivery' },
      { status: 'delivered', timestamp: new Date(Date.now() - 1000 * 60 * 10), message: 'Successfully delivered' },
    ],
    deliveryAgent: deliveryAgents[0],
    estimatedDelivery: 45,
    actualDelivery: 42,
    rating: 5,
    review: 'Excellent service and fresh products!',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2),
  },
]

export const analyticsData: AnalyticsData = {
  totalOrders: 12450,
  totalRevenue: 187650,
  averageOrderValue: 15.07,
  totalCustomers: 8234,
  activeDeliveryAgents: 156,
  avgDeliveryTime: 24,
  customerSatisfaction: 4.7,
  topProducts: mockProducts.slice(0, 5),
  revenueByCategory: [
    { category: 'Vegetables', revenue: 45234 },
    { category: 'Dairy & Eggs', revenue: 38900 },
    { category: 'Fruits', revenue: 34561 },
    { category: 'Bakery', revenue: 28345 },
    { category: 'Pantry Staples', revenue: 25610 },
    { category: 'Meat & Fish', revenue: 15000 },
  ],
  ordersByHour: [
    { hour: 0, orders: 45 },
    { hour: 1, orders: 32 },
    { hour: 6, orders: 87 },
    { hour: 7, orders: 156 },
    { hour: 8, orders: 234 },
    { hour: 9, orders: 312 },
    { hour: 12, orders: 456 },
    { hour: 18, orders: 389 },
    { hour: 19, orders: 298 },
    { hour: 20, orders: 267 },
    { hour: 21, orders: 198 },
  ],
  storePerformance: [
    { storeId: 'store-1', storeName: 'Downtown Fresh Market', revenue: 95234, orders: 6321, avgRating: 4.8 },
    { storeId: 'store-2', storeName: 'Uptown Premium Grocery', revenue: 67894, orders: 4501, avgRating: 4.7 },
    { storeId: 'store-3', storeName: 'Westside Organic Store', revenue: 24522, orders: 1628, avgRating: 4.6 },
  ],
}

export const businessMetrics: BusinessMetrics = {
  conversionsRate: 3.24,
  cartAbandonmentRate: 28.5,
  repeatCustomerRate: 62.3,
  avgSessionDuration: 8.4,
  peakOrderHours: [7, 8, 9, 12, 18, 19],
  customerLifetimeValue: 245.67,
  churnRate: 4.2,
  referralConversions: 12.5,
}

export const deliveryStatusSteps = [
  { key: 'pending', label: 'Order Placed', description: 'Your order has been placed' },
  { key: 'confirmed', label: 'Confirmed', description: 'Store confirmed your order' },
  { key: 'preparing', label: 'Preparing', description: 'Store is preparing your items' },
  { key: 'ready_for_pickup', label: 'Ready for Pickup', description: 'Order is ready' },
  { key: 'out_for_delivery', label: 'Out for Delivery', description: 'Delivery agent is on the way' },
  { key: 'delivered', label: 'Delivered', description: 'Order delivered successfully' },
]
